src/java/managedbeans/UserBean.java
package managedbeans;
import UI.userUI;
import UI.adminUI;
import DTO.userDTO;
import java.util.ArrayList;
import java.io.Serializable;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;


@Named(value = "user")
@SessionScoped
public class UserBean implements Serializable {

    private userUI user = new userUI();
    private userDTO userdetails = null;
    private boolean loginOK = false;
    private String username;
    private String password;
   
    
    public userDTO getUserInfo(){
        return userdetails;
    }
    
    public void setUserInfo(userDTO userdetails){
        this.userdetails = userdetails;
    }
    
     public void findUserDetails(String username)
    {
        userdetails = user.findUser(username);
       
    }
     

     //login stuff
     
    public String checkLogin(){
        try{
           this.setUserInfo(user.login(username, password));
           loginOK = true;
           if (loginOK){
            if (getUserInfo().getIsAdmin()){
                System.out.println("I've found an admin");
                return "admin";
            }else{
                System.out.println("Standard User found");
                return "showings";
            }
            
        }
        }catch(Exception ex){
          return null;  
        }
        
        
        return null;
    }
    private void clearLogin(){
        this.username = "";
        this.password= "";
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
    }
    
    public String logOut(){
        clearLogin();
        return "index";
    }

    public String getUsername()
    {
        return username;
    }

    public String getPassword()
    {
        return password;
    }
    
    public void setUsername(String username)
    {
        this.username = username;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }
    
}

src/java/managedbeans/showingBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbeans;



import DTO.showingDTO;
import UI.adminUI;
import UI.userUI;
import java.io.Serializable;
import java.util.ArrayList;
import javax.inject.Named;
import javax.inject.Inject;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;


@Named(value = "showing")
@SessionScoped
public class showingBean implements Serializable  {
    
    private adminUI admin = new adminUI();
    private userUI user = new userUI();
    private showingDTO showingdetails = null;
    
    
    @Inject
    screenBean screenBean;
    @Inject
    cinemaBean cinemaBean;
    
    public showingBean() {
    }
    
    public showingDTO getShowingInfo(){
        return showingdetails;
    }
    
    public String getShowingDetails(int showingID){
        showingdetails = user.findShowing(showingID);
        return "makebooking";
    }
    
    public void setShowingInfo(showingDTO showingdetails){
        this.showingdetails = showingdetails;
    }

    
    public ArrayList<showingDTO> getAllShowings(){
         ArrayList<showingDTO> allShowings = admin.getAllShowings();
         return allShowings;
     }
    
}

web/Login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Login</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
       <div align="center">
       <h:form>
            <h1> Login </h1>
            <h:panelGrid columns="2" styleClass="borderTable" rowClasses="tableRow">
            <h:outputText value="username: "/>
            <h:inputText value="#{user.username}"/>
            <h:outputText value="password: "/>
            <h:inputSecret value="#{user.password}"/>
            <h:commandButton type="submit" value="Login" action="#{user.checkLogin()}"/>
            <h:commandButton type="submit" value="Return to home" action="index"/>
            </h:panelGrid>
        </h:form>
       </div>
    </h:body>
</html>

web/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Admin Panel</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body> 
          <div class="container">
            <div class="header">
                <h:form>
                <h:commandButton type="submit" value="Home" action="index" immediate="true" />
                <h:commandButton type="submit" value="Showings" action="showings" immediate="true" />
                <h:commandButton type="submit" value="Register User" action="register" immediate="true" />
                <h:commandButton type="submit" value="Refresh aPanel" action="admin" immediate="true" />
                <h:commandButton type="submit" value="Logout" action="#{user.logOut()}" immediate="true" />
                <span>Admin Panel </span>
                </h:form>
            </div>
            
        </div>
        <div class="split left">
        <h:form>
            <h1>Add Showing</h1>
            <h:panelGrid columns="2" styleClass="borderTable">
            <h:outputText value="Film: "/>
            <h:inputText value="#{addShowing.filmID}"/>
            <h:outputText value="Screen: "/>
            <h:inputText value="#{addShowing.screenID}"/>
            <h:outputText value="Timeslot: "/>
            <h:inputText value="#{addShowing.timeslot}"/>

            <h:commandButton type="submit" value="Add Showing" action="#{addShowing.addShowing()}" />         
            </h:panelGrid>
        </h:form>
 
        <h:form>
            <h1>Add Film</h1>
            <h:panelGrid columns="2" styleClass="borderTable" rowClasses="tableRow">
            <h:outputText value="Film Title: "/>
            <h:inputText value="#{addFilm.title}"/>
            <h:outputText value="BBFC Age Rating: "/>
            <h:inputText value="#{addFilm.bbfcAge}"/>
            <h:outputText value="Runtime: "/>
            <h:inputText value="#{addFilm.runtime}"/>
            <h:outputText value="Leading Star: "/>
            <h:inputText value="#{addFilm.lead}"/>
            <h:commandButton type="submit" style="width:100px" value="Add Film" action="#{addFilm.addFilm()}" />         
            </h:panelGrid>
        </h:form>    
        </div>
        <div class="split right">
          
        <h:form>
            <h1> Film Manager </h1>
            <h:dataTable value="#{film.allFilms}"
                         var="flm"
                         styleClass="borderTable">   
                <h:column>
                    <f:facet name="header">filmID</f:facet>
                    <h:outputText value="#{flm.filmID}"/>
                </h:column> 
                           
                <h:column>
                    <f:facet name="header">title</f:facet>
                    <h:outputText value="#{flm.title}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">bbfcAge</f:facet>
                    <h:outputText value="#{flm.bbfcAge}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">runtime</f:facet>
                    <h:outputText value="#{flm.runtime}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">lead</f:facet>
                    <h:outputText value="#{flm.lead}"/>
                </h:column> 
                    
                <h:column>
                    <f:facet name="header">Admin</f:facet>
                    <h:commandButton value="Remove" action="#{removeFilm.removeFilm(flm.filmID)}" />
                </h:column>
            </h:dataTable>   
        </h:form>
        
            <h:form>
            <h1>Showing Manager</h1>
            <h:dataTable value="#{showing.allShowings}"
                         var="show"
                         styleClass="borderTable">   
                <h:column>
                    <f:facet name="header">ShowingID</f:facet>
                    <h:outputText value="#{show.showingID}"/>
                </h:column> 
                <h:column>
                    <f:facet name="header">Title</f:facet>
                    <h:outputText value="#{show.film.title}"/>
                </h:column> 
                           
                <h:column>
                    <f:facet name="header">Screen</f:facet>
                    <h:outputText value="#{show.screen.screenID}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">Showing Time</f:facet>
                    <h:outputText value="#{show.timeslot}"/>
                </h:column>
                
                <h:column>
                    <f:facet name="header">Admin</f:facet>
                    <h:commandButton value="Remove" action="#{removeShowing.removeShowing(show.showingID)}" />
                </h:column>
                           
            </h:dataTable>   
        </h:form>
           
        
        <h1>Screen Viewer </h1>
        <h:form>
            <h:dataTable value="#{screen.findAllScreens()}"
                         var="scr"
                         styleClass="borderTable">   
                <h:column>
                    <f:facet name="header">ScreenID</f:facet>
                    <h:outputText value="#{scr.screenID}"/>
                </h:column> 
                           
                <h:column>
                    <f:facet name="header">CinemaID</f:facet>
                    <h:outputText value="#{scr.cinema.cinemaID}"/>
                </h:column>   
            </h:dataTable>   
        </h:form>   
        </div>            
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Staffordshire University Cinema Portal</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="header">
                <h:form>
                <h:commandButton type="submit" value="Register" action="register" immediate="true"/>
                <h:commandButton type="submit" value="Login" action="Login" immediate="true"/>
                </h:form>
            </div>
            
        </div>
        
        
        <div align="center">
        <h1> Welcome to the Staffordshire University Cinema Portal </h1>
        
        <h:form>
            <h2> Currently Showing: </h2>
            <h:dataTable value="#{showing.allShowings}"
                         var="show"
                         styleClass="frontTable">   
                <h:column>
                    <f:facet name="header">Title</f:facet>
                    <h:outputText value="#{show.film.title}"/>
                </h:column> 
                           
                        
                <h:column>
                    <f:facet name="header">Showing Time</f:facet>
                    <h:outputText value="#{show.timeslot}"/>
                </h:column>             
            </h:dataTable> 
            <p> To book a showing please register/login! </p>
        </h:form>
        </div>
    </h:body>
</html>

web/makebooking.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Make a booking</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div align="center">
         <h:panelGrid columns="2" styleClass="borderTable">
        Here's some information for the booking you're about to make:
        <p> Film name: #{showing.showingInfo.film.title} </p>
        <p> Film Rating: #{showing.showingInfo.film.bbfcAge} </p>
        <p> Film Runtime: #{showing.showingInfo.film.runtime} hour(s) </p>
        <p> Starring: #{showing.showingInfo.film.lead} </p>
        <p> Showing at: #{showing.showingInfo.timeslot} </p>
        <p> At: #{showing.showingInfo.screen.cinema.name}, #{showing.showingInfo.screen.cinema.location} </p>
        <p> Screen: #{showing.showingInfo.screen.screenID} </p>
        
        Do you wish to confirm this booking?
        <h:form>
            <h:commandButton type="submit" value="Cancel" action="showings" immediate="true"/>
            <h:commandButton type="submit" value="Confirm" action="#{addBooking.addBooking()}" immediate="true"/>
        </h:form>
        </h:panelGrid>
        </div>
        
        
        
    </h:body>
</html>

web/manageAccount.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Manage Account</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="header">
                <h:form>
                <h:commandButton type="submit" value="Back" action="showings" immediate="true"/>
                </h:form>
            </div>
            
        </div>
        
        <h4> Note: You will be required to log back in after changing any details </h4>
         
        <h1> Current Address </h1>
        <p>#{user.userInfo.address1},#{user.userInfo.address2},#{user.userInfo.town},#{user.userInfo.county},#{user.userInfo.postcode}</p>
        
        <h:form>
            <h:panelGrid columns="2" styleClass="UserTable" rowClasses="borderTable">
            <h:outputText value="Address Line 1: "/>
            <h:inputText value="#{modifyUser.address1}"/>
            <h:outputText value="Address Line 2: "/>
            <h:inputText value="#{modifyUser.address2}"/>
            <h:outputText value="Town: "/>
            <h:inputText value="#{modifyUser.town}"/>
            <h:outputText value="County: "/>
            <h:inputText value="#{modifyUser.county}"/>
            <h:outputText value="Postcode: "/>
            <h:inputText value="#{modifyUser.postcode}"/>
            <h:commandButton type="submit" value="Update address" action="#{modifyUser.modifyUser()}" />  
            </h:panelGrid>
        </h:form>
    </h:body>
</html>

web/register.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Register</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div align="center">
        <h1> Create an account </h1>
        <h:form>
            <h:panelGrid columns="2" styleClass="borderTable" rowClasses="tableRow">
            <h:outputText value="username: "/>
            <h:inputText value="#{addUser.username}"/>
            <h:outputText value="password: "/>
            <h:inputText value="#{addUser.password}"/>
            <h:outputText value="Address Line 1: "/>
            <h:inputText value="#{addUser.address1}"/>
            <h:outputText value="Address Line 2: "/>
            <h:inputText value="#{addUser.address2}"/>
            <h:outputText value="Town: "/>
            <h:inputText value="#{addUser.town}"/>
            <h:outputText value="County: "/>
            <h:inputText value="#{addUser.county}"/>
            <h:outputText value="Postcode: "/>
            <h:inputText value="#{addUser.postcode}"/>
            <h:outputText value="DOB: "/>
            <h:inputText value="#{addUser.regdate}"> 
            <f:converter converterId="dateconv"/>
            </h:inputText>
            <h:commandButton type="submit" value="Create account" action="#{addUser.addUser()}" /> 
            <h:commandButton type="submit" value="Cancel" action="index" /> 
            </h:panelGrid>
            <h2>Creating an account allows you to book a showing at any of the cinemas </h2>
        </h:form>
        </div>
    </h:body>
</html>

web/showings.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Cinema Showings</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="header">
                <span>Hello,<b>#{user.userInfo.username}</b></span>
                <h:form>
                <h:commandButton type="submit" value="View Bookings" action="viewBookings" immediate="true"/>
                <h:commandButton type="submit" value="Modify Account" action="manageAccount" immediate="true"/>
                <h:commandButton type="submit" value="Logout" action="#{user.logOut()}" immediate="true"/>
                </h:form>
            </div>
            
        </div>
        <div align="center">
        <h1>Current Showings</h1>
        <h:form>
            <h:dataTable value="#{showing.allShowings}"
                         var="show"
                         styleClass="frontTable">   
                <h:column>
                    <f:facet name="header">Title</f:facet>
                    <h:outputText value="#{show.film.title}"/>
                </h:column> 
                           
                <h:column>
                    <f:facet name="header">Screen</f:facet>
                    <h:outputText value="#{show.screen.screenID}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">Showing Time</f:facet>
                    <h:outputText value="#{show.timeslot}"/>
                </h:column>
                
                <h:column>
                    <f:facet name="header">Options</f:facet>
                    <h:commandButton value="Book showing" action="#{showing.getShowingDetails(show.showingID)}" />
                </h:column>
                           
            </h:dataTable>   
        </h:form>
        <h2>You can view more information about a showing by clicking the 'view showing' button. </h2>
        </div>
        
    </h:body>
</html>

web/viewBookings.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>User Bookings</title>
        <h:outputStylesheet library="css" name="styles.css"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="header">
                <h:form>
                    <span>#{user.userInfo.username}'s bookings</span>    
                <h:commandButton type="submit" value="Back" action="showings" immediate="true"/>
                </h:form>
            </div>
            
        </div>
        
        <h:form>
            <h:dataTable value="#{booking.findUserBookings(user.userInfo.username)}"
                         var="book"
                         styleClass="frontTable">   
                <h:column>
                    <f:facet name="header">Booking Reference</f:facet>
                    <h:outputText value="#{book.bookingID}"/>
                </h:column> 
                
                 <h:column>
                    <f:facet name="header">Film</f:facet>
                    <h:outputText value="#{book.showing.film.title}"/>
                </h:column> 
                           
                <h:column>
                    <f:facet name="header">Cinema</f:facet>
                    <h:outputText value="#{book.showing.screen.cinema.location}"/>
                </h:column>
                        
                <h:column>
                    <f:facet name="header">Screen</f:facet>
                    <h:outputText value="#{book.showing.screen.screenID}"/>
                </h:column>
                
                <h:column>
                    <f:facet name="header">Options</f:facet>
                    <h:commandButton value="Cancel Booking" action="#{removeBooking.removeBooking(book.bookingID)}" />
                </h:column>
            </h:dataTable>   
        </h:form>
    </h:body>
</html>